spring:
  web:
    resources:
      static-locations: classpath:/uploads/  # Changed to use container path

  datasource:
    url: jdbc:postgresql://fms-db:5432/fms-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  mail:
    host: smtp.gmail.com
    port: 587
    username: aitelghariyasser@gmail.com
    password: "xhhr cjuc gwin dmnb"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret:
    key: "X1zA8!mN9@pQ#rT7$yV2^bK5&dF4*eG6(HzL0)wJ3_CxY"

server:
  port: 9999