version: '3.8'
services:
  postgres:
    container_name: fms
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=fms'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local